apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server1
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mycontainer
        image: australia-southeast2-docker.pkg.dev/sit737-388715/quickstart-docker-repo/quickstart-image:tag1
        ports:
        - containerPort: 8080
