apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server1
  labels:
    app: hello-server1
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: hello-server1
  template:
    metadata:
      labels:
        app: hello-server1
    spec:
      containers:
      - name: mynode
        image: gcr.io/sit737-388715/quickstart-docker-repo:latest
        ports:
        - containerPort: 8080